version: '3.9'

services:
  netflix_app:
    image: netflix_image
    container_name: netflix_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    restart: always
